import { VimCommand, ProficiencyPreset } from './types'
import { VIM_MODES, VimMode } from '../../../utils/constants'

export const vimCommands: VimCommand[] = [
  // Movement commands
  {
    key: 'h',
    modes: [VIM_MODES.NORMAL],
    description: 'Move cursor left',
    example: { before: 'he|llo', after: 'h|ello' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'j',
    modes: [VIM_MODES.NORMAL],
    description: 'Move cursor down',
    example: { before: 'lin|e 1\nline 2', after: 'line 1\nlin|e 2' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'k',
    modes: [VIM_MODES.NORMAL],
    description: 'Move cursor up',
    example: { before: 'line 1\nlin|e 2', after: 'lin|e 1\nline 2' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'l',
    modes: [VIM_MODES.NORMAL],
    description: 'Move cursor right',
    example: { before: 'h|ello', after: 'he|llo' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'w',
    modes: [VIM_MODES.NORMAL],
    description: 'Move to next word',
    example: { before: 'he|llo:world vim', after: 'hello|:world vim' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'W',
    modes: [VIM_MODES.NORMAL],
    description: 'Move to next WORD (whitespace separated)',
    example: { before: 'he|llo-world vim', after: 'hello-world |vim' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'b',
    modes: [VIM_MODES.NORMAL],
    description: 'Move to beginning of word',
    example: { before: 'hello world |vim', after: 'hello |world vim' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'B',
    modes: [VIM_MODES.NORMAL],
    description: 'Move to beginning of WORD (whitespace separated)',
    example: { before: 'hello world-|vim', after: 'hello |world-vim' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'e',
    modes: [VIM_MODES.NORMAL],
    description: 'Move to end of word',
    example: { before: 'hell|o world', after: 'hello worl|d' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'E',
    modes: [VIM_MODES.NORMAL],
    description: 'Move to end of WORD (whitespace separated)',
    example: { before: 'hell|o-world vim', after: 'hello-worl|d vim' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: '0',
    modes: [VIM_MODES.NORMAL],
    description: 'Move to start of line',
    example: { before: '  hello wo|rld', after: '|  hello world' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: '^',
    modes: [VIM_MODES.NORMAL],
    description: 'Move to first non-blank character',
    example: { before: '  hello wo|rld', after: '  |hello world' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: '$',
    modes: [VIM_MODES.NORMAL],
    description: 'Move to end of line',
    example: { before: 'hello |world', after: 'hello worl|d' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: '_',
    modes: [VIM_MODES.NORMAL],
    description: 'Move to first non-blank character of line',
    example: { before: '  hello wo|rld', after: '  |hello world' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'f',
    modes: [VIM_MODES.NORMAL],
    description: 'Find character forward (followed by character)',
    example: { before: 'h|ello world', after: 'hell|o world' },
    category: 'search',
    colorClass: 'purple',
  },
  {
    key: 'F',
    modes: [VIM_MODES.NORMAL],
    description: 'Find character backward (followed by character)',
    example: { before: 'hello worl|d', after: 'he|llo world' },
    category: 'search',
    colorClass: 'purple',
  },
  {
    key: 't',
    modes: [VIM_MODES.NORMAL],
    description: 'Till character forward (followed by character)',
    example: { before: '|hello world', after: 'hel|lo world' },
    category: 'search',
    colorClass: 'purple',
  },
  {
    key: 'T',
    modes: [VIM_MODES.NORMAL],
    description: 'Till character backward (followed by character)',
    example: { before: 'hello worl|d', after: 'hel|lo world' },
    category: 'search',
    colorClass: 'purple',
  },
  {
    key: ';',
    modes: [VIM_MODES.NORMAL],
    description: 'Repeat last f, F, t, or T motion forward',
    example: { before: 'h|ello hello', after: 'hello h|ello' },
    category: 'search',
    colorClass: 'purple',
  },
  {
    key: ',',
    modes: [VIM_MODES.NORMAL],
    description: 'Repeat last f, F, t, or T motion backward',
    example: { before: 'hello h|ello', after: 'h|ello hello' },
    category: 'search',
    colorClass: 'purple',
  },
  {
    key: 'g',
    modes: [VIM_MODES.NORMAL],
    description: 'Go to commands (gg = top, G = bottom)',
    example: {
      before: 'line 1\nline |2\nline 3',
      after: '|line 1\nline 2\nline 3',
    },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'G',
    modes: [VIM_MODES.NORMAL],
    description: 'Go to last line',
    example: {
      before: 'line |1\nline 2\nline 3',
      after: 'line 1\nline 2\nline |3',
    },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'H',
    modes: [VIM_MODES.NORMAL],
    description: 'Move to top of screen (High)',
    example: {
      before: 'line 1\nline 2\nline |3',
      after: 'line |1\nline 2\nline 3',
    },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'M',
    modes: [VIM_MODES.NORMAL],
    description: 'Move to middle of screen (Middle)',
    example: {
      before: 'line 1\nline 2\nline |3',
      after: 'line 1\nline |2\nline |3',
    },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'L',
    modes: [VIM_MODES.NORMAL],
    description: 'Move to bottom of screen (Low)',
    example: {
      before: 'lin|e 1\nline 2\nline 3',
      after: 'line 1\nline 2\nlin|e 3',
    },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: '%',
    modes: [VIM_MODES.NORMAL],
    description: 'Jump to matching bracket/paren',
    example: { before: '|(hello)', after: '(hello|)' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: '{',
    modes: [VIM_MODES.NORMAL],
    description: 'Jump to previous paragraph',
    example: {
      before: 'text\n\nparagraph\nhe|llo\nmore',
      after: 'text\n|\n\nparagraph\nhello\nmore',
    },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: '}',
    modes: [VIM_MODES.NORMAL],
    description: 'Jump to next paragraph',
    example: {
      before: 'text\n\npara|graph\nhello\n\nmore',
      after: 'text\n\nparagraph\nhello\n|\n\nmore',
    },
    category: 'movement',
    colorClass: 'emerald',
  },
  // {
  //   key: '[',
  //   modes: [VIM_MODES.NORMAL],
  //   description: 'Section backward motions (combined with other keys)',
  //   example: {
  //     before: 'func1()\n\nfunc|2()\n\nfunc3()',
  //     after: 'func1()\n|\nfunc2()\n\nfunc3()',
  //   },
  //   category: 'movement',
  //   colorClass: 'emerald',
  // },
  // {
  //   key: ']',
  //   modes: [VIM_MODES.NORMAL],
  //   description: 'Section forward motions (combined with other keys)',
  //   example: {
  //     before: 'func1()\n\nfunc|2()\n\nfunc3()',
  //     after: 'func1()\n\nfunc2()\n|\nfunc3()',
  //   },
  //   category: 'movement',
  //   colorClass: 'emerald',
  // },

  // Search commands
  {
    key: '*',
    modes: [VIM_MODES.NORMAL],
    description: 'Search forward for word under cursor',
    example: { before: 'vi|m is awesome vim', after: 'vim is awesome |vim' },
    category: 'search',
    colorClass: 'purple',
  },
  {
    key: '/',
    modes: [VIM_MODES.NORMAL],
    description: 'Search forward',
    example: { before: 'vim i|s awesome vim', after: 'vim is awesome |vim' },
    category: 'search',
    colorClass: 'purple',
  },
  {
    key: '?',
    modes: [VIM_MODES.NORMAL],
    description: 'Search backward',
    example: { before: 'vim is aweso|me vim', after: '|vim is awesome vim' },
    category: 'search',
    colorClass: 'purple',
  },
  {
    key: 'n',
    modes: [VIM_MODES.NORMAL],
    description: 'Next search match',
    example: { before: '|vim text vim more', after: 'vim text |vim more' },
    category: 'search',
    colorClass: 'purple',
  },
  {
    key: 'N',
    modes: [VIM_MODES.NORMAL],
    description: 'Previous search match',
    example: { before: 'vim text |vim more', after: '|vim text vim more' },
    category: 'search',
    colorClass: 'purple',
  },

  // Insert mode commands (lowercase)
  {
    key: 'i',
    modes: [VIM_MODES.NORMAL],
    description: 'Insert before cursor',
    example: { before: 'hel|lo (NORMAL)', after: 'hel|lo (INSERT)' },
    category: 'mode',
    colorClass: 'blue',
  },
  {
    key: 'I',
    modes: [VIM_MODES.NORMAL],
    description: 'Insert at beginning of line',
    example: { before: '  hel|lo (NORMAL)', after: '  |hello (INSERT)' },
    category: 'mode',
    colorClass: 'blue',
  },
  {
    key: 'a',
    modes: [VIM_MODES.NORMAL],
    description: 'Insert after cursor',
    example: { before: 'hel|lo (NORMAL)', after: 'hell|o (INSERT)' },
    category: 'mode',
    colorClass: 'blue',
  },
  {
    key: 'A',
    modes: [VIM_MODES.NORMAL],
    description: 'Insert at end of line',
    example: {
      before: 'hel|lo world (NORMAL)',
      after: 'hello world| (INSERT)',
    },
    category: 'mode',
    colorClass: 'blue',
  },
  {
    key: 'o',
    modes: [VIM_MODES.NORMAL],
    description: 'Insert new line below',
    example: { before: 'text|', after: 'text\n| (INSERT)' },
    category: 'mode',
    colorClass: 'blue',
  },
  {
    key: 'O',
    modes: [VIM_MODES.NORMAL],
    description: 'Insert new line above',
    example: { before: 'text|', after: '| (INSERT)\ntext' },
    category: 'mode',
    colorClass: 'blue',
  },
  {
    key: 'Escape',
    modes: [VIM_MODES.INSERT],
    description: 'Return to normal mode',
    example: { before: 'hel|lo (INSERT)', after: 'he|llo (NORMAL)' },
    category: 'mode',
    colorClass: 'blue',
  },

  // Delete commands
  {
    key: 'x',
    modes: [VIM_MODES.NORMAL],
    description: 'Delete character under cursor',
    example: { before: 'hel|lo', after: 'hel|o' },
    category: 'delete',
    colorClass: 'red',
  },
  {
    key: 'X',
    modes: [VIM_MODES.NORMAL],
    description: 'Delete character before cursor',
    example: { before: 'hel|lo', after: 'he|lo' },
    category: 'delete',
    colorClass: 'red',
  },
  {
    key: 'd',
    modes: [VIM_MODES.NORMAL],
    description: 'Delete operator (combine with motion: dw, dd, etc)',
    example: { before: 'hello |world vim', after: 'hello |vim' },
    category: 'delete',
    colorClass: 'red',
  },
  {
    key: 'D',
    modes: [VIM_MODES.NORMAL],
    description: 'Delete to end of line',
    example: { before: 'hello |world vim', after: 'hello |' },
    category: 'delete',
    colorClass: 'red',
  },
  {
    key: 'c',
    modes: [VIM_MODES.NORMAL],
    description: 'Change operator (combine with motion: cw, cc, etc)',
    example: { before: 'hello |world vim', after: 'hello | vim (INSERT)' },
    category: 'editing',
    colorClass: 'red',
  },
  {
    key: 'C',
    modes: [VIM_MODES.NORMAL],
    description: 'Change to end of line',
    example: { before: 'hello |world vim', after: 'hello | (INSERT)' },
    category: 'editing',
    colorClass: 'red',
  },
  {
    key: 'J',
    modes: [VIM_MODES.NORMAL],
    description: 'Join current line with next line',
    example: { before: 'he|llo\nworld', after: 'hello| world' },
    category: 'editing',
    colorClass: 'amber',
  },

  // Yank (copy) and paste commands
  {
    key: 'y',
    modes: [VIM_MODES.NORMAL],
    description: 'Yank (copy) operator (combine with motion: yw, yy, etc)',
    example: { before: 'hello |world vim', after: 'hello |world vim (copied)' },
    category: 'editing',
    colorClass: 'amber',
  },
  {
    key: 'p',
    modes: [VIM_MODES.NORMAL],
    description: 'Paste after cursor',
    example: { before: 'hello |world', after: 'hello world| (pasted text)' },
    category: 'editing',
    colorClass: 'amber',
  },
  {
    key: 'P',
    modes: [VIM_MODES.NORMAL],
    description: 'Paste before cursor',
    example: { before: 'hello |world', after: 'hello |(pasted text) world' },
    category: 'editing',
    colorClass: 'amber',
  },

  // History commands
  {
    key: 'u',
    modes: [VIM_MODES.NORMAL],
    description: 'Undo last change',
    example: { before: 'hello worl|d', after: 'hello |' },
    category: 'history',
    colorClass: 'amber',
  },
  {
    key: 'r',
    modes: [VIM_MODES.NORMAL],
    description: 'Replace character under cursor (followed by character)',
    example: { before: 'hel|lo', after: 'hel|xo' },
    category: 'editing',
    colorClass: 'red',
  },
  {
    key: '.',
    modes: [VIM_MODES.NORMAL],
    description: 'Repeat last change',
    example: { before: 'hello |world', after: 'hello |worldworld' },
    category: 'history',
    colorClass: 'amber',
  },

  // Marks and jumps
  {
    key: 'm',
    modes: [VIM_MODES.NORMAL],
    description: 'Set mark (followed by letter)',
    example: { before: 'hel|lo world', after: 'hel|lo world (mark set)' },
    category: 'movement',
    colorClass: 'purple',
  },
  {
    key: "'",
    modes: [VIM_MODES.NORMAL],
    description: 'Jump to mark (followed by letter)',
    example: { before: 'hello |world', after: 'hel|lo world' },
    category: 'movement',
    colorClass: 'purple',
  },
  {
    key: '@',
    modes: [VIM_MODES.NORMAL],
    description: 'Execute macro (followed by register letter)',
    example: { before: 'hel|lo', after: 'hel|lo (macro executed)' },
    category: 'editing',
    colorClass: 'purple',
  },

  // Special keys with text explanations
  {
    key: 'Backspace',
    modes: [VIM_MODES.INSERT],
    description: 'Delete character before cursor (in insert mode)',
    example: { before: 'hell|o', after: 'hel|o' },
    category: 'editing',
    colorClass: 'red',
  },
  {
    key: 'Enter',
    modes: [VIM_MODES.INSERT],
    description: 'Insert new line (in insert mode)',
    example: { before: 'hello|world', after: 'hello\n|world' },
    category: 'editing',
    colorClass: 'blue',
  },
]

export const proficiencyPresets: ProficiencyPreset[] = [
  {
    level: 'beginner',
    title: 'Beginner',
    description: 'Essential movement and basic insert mode',
    highlightedKeys: ['h', 'j', 'k', 'l', 'i', 'Escape'],
  },
  {
    level: 'intermediate',
    title: 'Intermediate',
    description: 'Word navigation, line operations, and more insert commands',
    highlightedKeys: [
      'h',
      'j',
      'k',
      'l',
      'w',
      'b',
      'e',
      '0',
      '$',
      'i',
      'I',
      'a',
      'A',
      'o',
      'O',
      'x',
      'Escape',
    ],
  },
  {
    level: 'advanced',
    title: 'Advanced',
    description: 'Search, operators, and efficient editing',
    highlightedKeys: [
      'h',
      'j',
      'k',
      'l',
      'w',
      'W',
      'b',
      'B',
      'e',
      'E',
      '0',
      '$',
      '^',
      'f',
      'F',
      't',
      'T',
      '/',
      '?',
      'n',
      'N',
      'i',
      'I',
      'a',
      'A',
      'o',
      'O',
      'x',
      'X',
      'd',
      'D',
      'c',
      'C',
      'u',
      'Escape',
    ],
  },
  {
    level: 'expert',
    title: 'Expert',
    description: 'Advanced motions, marks, and power user features',
    highlightedKeys: [
      'h',
      'j',
      'k',
      'l',
      'w',
      'W',
      'b',
      'B',
      'e',
      'E',
      '0',
      '$',
      '^',
      'f',
      'F',
      't',
      'T',
      '/',
      '?',
      'n',
      'N',
      'g',
      'G',
      '%',
      'm',
      "'",
      'i',
      'I',
      'a',
      'A',
      'o',
      'O',
      'x',
      'X',
      'd',
      'D',
      'c',
      'C',
      'y',
      'p',
      'P',
      'u',
      'r',
      '.',
      '@',
      'Escape',
    ],
  },
]

// Helper to get command for a key in a specific mode (case-sensitive)
export const getCommandForKey = (
  key: string,
  mode: string,
): VimCommand | undefined => {
  return vimCommands.find(
    (cmd) => cmd.key === key && cmd.modes.includes(mode as VimMode),
  )
}
