import { VimCommand, ProficiencyPreset } from './types'
import { VIM_MODES, VimMode } from '../../../utils/constants'

export const vimCommands: VimCommand[] = [
  // Movement commands
  {
    key: 'h',
    modes: [VIM_MODES.NORMAL],
    description: 'Move cursor left',
    example: { before: 'he|llo', after: 'h|ello' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'j',
    modes: [VIM_MODES.NORMAL],
    description: 'Move cursor down',
    example: { before: 'lin|e 1\nline 2', after: 'line 1\nlin|e 2' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'k',
    modes: [VIM_MODES.NORMAL],
    description: 'Move cursor up',
    example: { before: 'line 1\nlin|e 2', after: 'lin|e 1\nline 2' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'l',
    modes: [VIM_MODES.NORMAL],
    description: 'Move cursor right',
    example: { before: 'h|ello', after: 'he|llo' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'w',
    modes: [VIM_MODES.NORMAL],
    description: 'Move to next word',
    example: { before: 'he|llo:world vim', after: 'hello|:world vim' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'W',
    modes: [VIM_MODES.NORMAL],
    description: 'Move to next WORD (whitespace separated)',
    example: { before: 'he|llo-world vim', after: 'hello-world |vim' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'b',
    modes: [VIM_MODES.NORMAL],
    description: 'Move to beginning of word',
    example: { before: 'hello world |vim', after: 'hello |world vim' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'B',
    modes: [VIM_MODES.NORMAL],
    description: 'Move to beginning of WORD (whitespace separated)',
    example: { before: 'hello world-|vim', after: 'hello |world-vim' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'e',
    modes: [VIM_MODES.NORMAL],
    description: 'Move to end of word',
    example: { before: 'hell|o world', after: 'hello worl|d' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'E',
    modes: [VIM_MODES.NORMAL],
    description: 'Move to end of WORD (whitespace separated)',
    example: { before: 'hell|o-world vim', after: 'hello-worl|d vim' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: '0',
    modes: [VIM_MODES.NORMAL],
    description: 'Move to start of line',
    example: { before: '  hello wo|rld', after: '|  hello world' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: '^',
    modes: [VIM_MODES.NORMAL],
    description: 'Move to first non-blank character',
    example: { before: '  hello wo|rld', after: '  |hello world' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: '$',
    modes: [VIM_MODES.NORMAL],
    description: 'Move to end of line',
    example: { before: 'hello |world', after: 'hello worl|d' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: '_',
    modes: [VIM_MODES.NORMAL],
    description: 'Move to first non-blank character of line',
    example: { before: '  hello wo|rld', after: '  |hello world' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'f',
    modes: [VIM_MODES.NORMAL],
    description: 'Find character forward (followed by character)',
    example: { before: 'h|ello world', after: 'hell|o world' },
    category: 'search',
    colorClass: 'purple',
  },
  {
    key: 'F',
    modes: [VIM_MODES.NORMAL],
    description: 'Find character backward (followed by character)',
    example: { before: 'hello worl|d', after: 'he|llo world' },
    category: 'search',
    colorClass: 'purple',
  },
  {
    key: 't',
    modes: [VIM_MODES.NORMAL],
    description: 'Till character forward (followed by character)',
    example: { before: '|hello world', after: 'hel|lo world' },
    category: 'search',
    colorClass: 'purple',
  },
  {
    key: 'T',
    modes: [VIM_MODES.NORMAL],
    description: 'Till character backward (followed by character)',
    example: { before: 'hello worl|d', after: 'hel|lo world' },
    category: 'search',
    colorClass: 'purple',
  },
  {
    key: ';',
    modes: [VIM_MODES.NORMAL],
    description: 'Repeat last f, F, t, or T motion forward',
    example: { before: 'h|ello hello', after: 'hello h|ello' },
    category: 'search',
    colorClass: 'purple',
  },
  {
    key: ',',
    modes: [VIM_MODES.NORMAL],
    description: 'Repeat last f, F, t, or T motion backward',
    example: { before: 'hello h|ello', after: 'h|ello hello' },
    category: 'search',
    colorClass: 'purple',
  },
  {
    key: 'g',
    modes: [VIM_MODES.NORMAL],
    description: 'Go to commands (gg = top, G = bottom)',
    example: {
      before: 'line 1\nline |2\nline 3',
      after: '|line 1\nline 2\nline 3',
    },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'G',
    modes: [VIM_MODES.NORMAL],
    description: 'Go to last line',
    example: {
      before: 'line |1\nline 2\nline 3',
      after: 'line 1\nline 2\nline |3',
    },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'H',
    modes: [VIM_MODES.NORMAL],
    description: 'Move to top of screen (High)',
    example: {
      before: 'line 1\nline 2\nline |3',
      after: 'line |1\nline 2\nline 3',
    },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'M',
    modes: [VIM_MODES.NORMAL],
    description: 'Move to middle of screen (Middle)',
    example: {
      before: 'line 1\nline 2\nline |3',
      after: 'line 1\nline |2\nline |3',
    },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'L',
    modes: [VIM_MODES.NORMAL],
    description: 'Move to bottom of screen (Low)',
    example: {
      before: 'lin|e 1\nline 2\nline 3',
      after: 'line 1\nline 2\nlin|e 3',
    },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: '%',
    modes: [VIM_MODES.NORMAL],
    description: 'Jump to matching bracket/paren',
    example: { before: '|(hello)', after: '(hello|)' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: '{',
    modes: [VIM_MODES.NORMAL],
    description: 'Jump to previous paragraph',
    example: {
      before: 'text\n\nparagraph\nhe|llo\nmore',
      after: 'text\n|\n\nparagraph\nhello\nmore',
    },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: '}',
    modes: [VIM_MODES.NORMAL],
    description: 'Jump to next paragraph',
    example: {
      before: 'text\n\npara|graph\nhello\n\nmore',
      after: 'text\n\nparagraph\nhello\n|\n\nmore',
    },
    category: 'movement',
    colorClass: 'emerald',
  },
  // {
  //   key: '[',
  //   modes: [VIM_MODES.NORMAL],
  //   description: 'Section backward motions (combined with other keys)',
  //   example: {
  //     before: 'func1()\n\nfunc|2()\n\nfunc3()',
  //     after: 'func1()\n|\nfunc2()\n\nfunc3()',
  //   },
  //   category: 'movement',
  //   colorClass: 'emerald',
  // },
  // {
  //   key: ']',
  //   modes: [VIM_MODES.NORMAL],
  //   description: 'Section forward motions (combined with other keys)',
  //   example: {
  //     before: 'func1()\n\nfunc|2()\n\nfunc3()',
  //     after: 'func1()\n\nfunc2()\n|\nfunc3()',
  //   },
  //   category: 'movement',
  //   colorClass: 'emerald',
  // },

  // Search commands
  {
    key: '*',
    modes: [VIM_MODES.NORMAL],
    description: 'Search forward for word under cursor',
    example: { before: 'vi|m is awesome vim', after: 'vim is awesome |vim' },
    category: 'search',
    colorClass: 'purple',
  },
  {
    key: '/',
    modes: [VIM_MODES.NORMAL],
    description: 'Search forward',
    example: { before: 'vim i|s awesome vim', after: 'vim is awesome |vim' },
    category: 'search',
    colorClass: 'purple',
  },
  {
    key: '?',
    modes: [VIM_MODES.NORMAL],
    description: 'Search backward',
    example: { before: 'vim is aweso|me vim', after: '|vim is awesome vim' },
    category: 'search',
    colorClass: 'purple',
  },
  {
    key: 'n',
    modes: [VIM_MODES.NORMAL],
    description: 'Next search match',
    example: { before: '|vim text vim more', after: 'vim text |vim more' },
    category: 'search',
    colorClass: 'purple',
  },
  {
    key: 'N',
    modes: [VIM_MODES.NORMAL],
    description: 'Previous search match',
    example: { before: 'vim text |vim more', after: '|vim text vim more' },
    category: 'search',
    colorClass: 'purple',
  },

  // Insert mode commands (lowercase)
  {
    key: 'i',
    modes: [VIM_MODES.NORMAL],
    description: 'Insert before cursor',
    example: { before: 'hel|lo (NORMAL)', after: 'hel|lo (INSERT)' },
    category: 'mode',
    colorClass: 'blue',
  },
  {
    key: 'I',
    modes: [VIM_MODES.NORMAL],
    description: 'Insert at beginning of line',
    example: { before: '  hel|lo (NORMAL)', after: '  |hello (INSERT)' },
    category: 'mode',
    colorClass: 'blue',
  },
  {
    key: 'a',
    modes: [VIM_MODES.NORMAL],
    description: 'Insert after cursor',
    example: { before: 'hel|lo (NORMAL)', after: 'hell|o (INSERT)' },
    category: 'mode',
    colorClass: 'blue',
  },
  {
    key: 'A',
    modes: [VIM_MODES.NORMAL],
    description: 'Insert at end of line',
    example: {
      before: 'hel|lo world (NORMAL)',
      after: 'hello world| (INSERT)',
    },
    category: 'mode',
    colorClass: 'blue',
  },
  {
    key: 'o',
    modes: [VIM_MODES.NORMAL],
    description: 'Insert new line below',
    example: { before: 'text|', after: 'text\n| (INSERT)' },
    category: 'mode',
    colorClass: 'blue',
  },
  {
    key: 'O',
    modes: [VIM_MODES.NORMAL],
    description: 'Insert new line above',
    example: { before: 'text|', after: '| (INSERT)\ntext' },
    category: 'mode',
    colorClass: 'blue',
  },
  {
    key: 'Escape',
    modes: [VIM_MODES.INSERT],
    description: 'Return to normal mode',
    example: { before: 'hel|lo (INSERT)', after: 'he|llo (NORMAL)' },
    category: 'mode',
    colorClass: 'blue',
  },

  // Delete commands
  {
    key: 'x',
    modes: [VIM_MODES.NORMAL],
    description: 'Delete character under cursor',
    example: { before: 'hel|lo', after: 'hel|o' },
    category: 'delete',
    colorClass: 'red',
  },
  {
    key: 'X',
    modes: [VIM_MODES.NORMAL],
    description: 'Delete character before cursor',
    example: { before: 'hel|lo', after: 'he|lo' },
    category: 'delete',
    colorClass: 'red',
  },
  {
    key: 's',
    modes: [VIM_MODES.NORMAL],
    description: 'Substitute character (delete and enter insert mode)',
    example: { before: 'hel|lo', after: 'hel|o (INSERT)' },
    category: 'editing',
    colorClass: 'red',
  },
  {
    key: 'S',
    modes: [VIM_MODES.NORMAL],
    description: 'Substitute line (delete line and enter insert mode)',
    example: { before: '  hel|lo world', after: '  | (INSERT)' },
    category: 'editing',
    colorClass: 'red',
  },
  {
    key: 'd',
    modes: [VIM_MODES.NORMAL],
    description: 'Delete operator (combine with motion: dw, dd, etc)',
    example: { before: 'hello |world vim', after: 'hello |vim' },
    category: 'delete',
    colorClass: 'red',
  },
  {
    key: 'D',
    modes: [VIM_MODES.NORMAL],
    description: 'Delete to end of line',
    example: { before: 'hello |world vim', after: 'hello |' },
    category: 'delete',
    colorClass: 'red',
  },
  {
    key: 'c',
    modes: [VIM_MODES.NORMAL],
    description: 'Change operator (combine with motion: cw, cc, etc)',
    example: { before: 'hello |world vim', after: 'hello | vim (INSERT)' },
    category: 'editing',
    colorClass: 'red',
  },
  {
    key: 'C',
    modes: [VIM_MODES.NORMAL],
    description: 'Change to end of line',
    example: { before: 'hello |world vim', after: 'hello | (INSERT)' },
    category: 'editing',
    colorClass: 'red',
  },
  {
    key: 'J',
    modes: [VIM_MODES.NORMAL],
    description: 'Join current line with next line',
    example: { before: 'he|llo\nworld', after: 'hello| world' },
    category: 'editing',
    colorClass: 'amber',
  },

  // Yank (copy) and paste commands
  {
    key: 'y',
    modes: [VIM_MODES.NORMAL],
    description: 'Yank (copy) operator (combine with motion: yw, yy, etc)',
    example: { before: 'hello |world vim', after: 'hello |world vim (copied)' },
    category: 'editing',
    colorClass: 'amber',
  },
  {
    key: 'p',
    modes: [VIM_MODES.NORMAL],
    description: 'Paste after cursor',
    example: { before: 'hello |world', after: 'hello world| (pasted text)' },
    category: 'editing',
    colorClass: 'amber',
  },
  {
    key: 'P',
    modes: [VIM_MODES.NORMAL],
    description: 'Paste before cursor',
    example: { before: 'hello |world', after: 'hello |(pasted text) world' },
    category: 'editing',
    colorClass: 'amber',
  },

  // History commands
  {
    key: 'u',
    modes: [VIM_MODES.NORMAL],
    description: 'Undo last change',
    example: { before: 'hello worl|d', after: 'hello |' },
    category: 'history',
    colorClass: 'amber',
  },
  {
    key: 'r',
    modes: [VIM_MODES.NORMAL],
    description: 'Replace character under cursor (followed by character)',
    example: { before: 'hel|lo', after: 'hel|xo' },
    category: 'editing',
    colorClass: 'red',
  },
  {
    key: '.',
    modes: [VIM_MODES.NORMAL],
    description: 'Repeat last change',
    example: { before: 'hello |world', after: 'hello |worldworld' },
    category: 'history',
    colorClass: 'amber',
  },

  // Marks and jumps
  {
    key: 'm',
    modes: [VIM_MODES.NORMAL],
    description: 'Set mark (followed by letter)',
    example: { before: 'hel|lo world', after: 'hel|lo world (mark set)' },
    category: 'movement',
    colorClass: 'purple',
  },
  {
    key: "'",
    modes: [VIM_MODES.NORMAL],
    description: 'Jump to mark (followed by letter)',
    example: { before: 'hello |world', after: 'hel|lo world' },
    category: 'movement',
    colorClass: 'purple',
  },
  {
    key: '@',
    modes: [VIM_MODES.NORMAL],
    description: 'Execute macro (followed by register letter)',
    example: { before: 'hel|lo', after: 'hel|lo (macro executed)' },
    category: 'editing',
    colorClass: 'purple',
  },

  // Special keys with text explanations
  {
    key: 'Backspace',
    modes: [VIM_MODES.INSERT],
    description: 'Delete character before cursor (in insert mode)',
    example: { before: 'hell|o', after: 'hel|o' },
    category: 'editing',
    colorClass: 'red',
  },
  {
    key: 'Backspace',
    modes: [VIM_MODES.NORMAL],
    description: 'Move cursor left (same as h)',
    example: { before: 'hel|lo', after: 'he|llo' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'Enter',
    modes: [VIM_MODES.INSERT],
    description: 'Insert new line (in insert mode)',
    example: { before: 'hello|world', after: 'hello\n|world' },
    category: 'editing',
    colorClass: 'blue',
  },
  {
    key: 'Enter',
    modes: [VIM_MODES.NORMAL],
    description: 'Move to first non-blank character of next line',
    example: {
      before: 'line 1|\nline 2\nline 3',
      after: 'line 1\n|line 2\nline 3',
    },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'Escape',
    modes: [VIM_MODES.NORMAL],
    description: 'Cancel pending command or count. Go back to NORMAL mode.',
    example: { before: '5d|', after: '|' },
    category: 'mode',
    colorClass: 'blue',
  },

  // ========================================
  // VISUAL MODE COMMANDS
  // ========================================

  // Visual mode entry commands (from Normal mode)
  {
    key: 'v',
    modes: [VIM_MODES.NORMAL],
    description: 'Enter visual (character) mode',
    example: { before: 'hel|lo world (NORMAL)', after: 'hel|lo world (VISUAL)' },
    category: 'mode',
    colorClass: 'purple',
  },
  {
    key: 'V',
    modes: [VIM_MODES.NORMAL],
    description: 'Enter visual line mode (select entire lines)',
    example: {
      before: 'hel|lo world (NORMAL)',
      after: '|hello world (VISUAL LINE)',
    },
    category: 'mode',
    colorClass: 'purple',
  },

  // Movement commands in Visual mode (extend selection)
  {
    key: 'h',
    modes: [VIM_MODES.VISUAL],
    description: 'Extend selection left',
    example: { before: 'he[ll]o', after: 'h[ell]o' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'j',
    modes: [VIM_MODES.VISUAL],
    description: 'Extend selection down',
    example: { before: 'lin[e 1]\nline 2', after: 'lin[e 1\nline] 2' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'k',
    modes: [VIM_MODES.VISUAL],
    description: 'Extend selection up',
    example: { before: 'line 1\nlin[e 2]', after: 'lin[e 1\nline] 2' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'l',
    modes: [VIM_MODES.VISUAL],
    description: 'Extend selection right',
    example: { before: 'h[el]lo', after: 'h[ell]o' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'w',
    modes: [VIM_MODES.VISUAL],
    description: 'Extend selection to next word',
    example: { before: 'he[llo] world', after: 'he[llo world]' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'W',
    modes: [VIM_MODES.VISUAL],
    description: 'Extend selection to next WORD (whitespace separated)',
    example: { before: 'he[llo-]world vim', after: 'he[llo-world] vim' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'b',
    modes: [VIM_MODES.VISUAL],
    description: 'Extend selection to previous word',
    example: { before: 'hello [world]', after: '[hello world]' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'B',
    modes: [VIM_MODES.VISUAL],
    description: 'Extend selection to previous WORD',
    example: { before: 'hello world-[vim]', after: '[hello world-vim]' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'e',
    modes: [VIM_MODES.VISUAL],
    description: 'Extend selection to end of word',
    example: { before: 'he[ll]o world', after: 'he[llo] world' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'E',
    modes: [VIM_MODES.VISUAL],
    description: 'Extend selection to end of WORD',
    example: { before: 'he[ll]o-world vim', after: 'he[llo-world] vim' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: '0',
    modes: [VIM_MODES.VISUAL],
    description: 'Extend selection to start of line',
    example: { before: '  hello [world]', after: '[  hello world]' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: '$',
    modes: [VIM_MODES.VISUAL],
    description: 'Extend selection to end of line',
    example: { before: 'hello [wor]ld', after: 'hello [world]' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: '^',
    modes: [VIM_MODES.VISUAL],
    description: 'Extend selection to first non-blank character',
    example: { before: '  hello [world]', after: '  [hello world]' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'G',
    modes: [VIM_MODES.VISUAL],
    description: 'Extend selection to last line',
    example: {
      before: '[line 1]\nline 2\nline 3',
      after: '[line 1\nline 2\nline 3]',
    },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'g',
    modes: [VIM_MODES.VISUAL],
    description: 'Go commands (gg = extend to top)',
    example: {
      before: 'line 1\nline 2\n[line 3]',
      after: '[line 1\nline 2\nline 3]',
    },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: '%',
    modes: [VIM_MODES.VISUAL],
    description: 'Extend selection to matching bracket',
    example: { before: '|[(hello)]', after: '[(hello)|]' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: '{',
    modes: [VIM_MODES.VISUAL],
    description: 'Extend selection to previous paragraph',
    example: {
      before: 'text\n\n[paragraph]',
      after: '[text\n\nparagraph]',
    },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: '}',
    modes: [VIM_MODES.VISUAL],
    description: 'Extend selection to next paragraph',
    example: {
      before: '[text]\n\nparagraph',
      after: '[text\n\nparagraph]',
    },
    category: 'movement',
    colorClass: 'emerald',
  },

  // Selection modifiers
  {
    key: 'o',
    modes: [VIM_MODES.VISUAL],
    description: 'Toggle cursor to other end of selection',
    example: { before: '|hello world]', after: '[hello world|' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'O',
    modes: [VIM_MODES.VISUAL],
    description: 'Toggle cursor to other corner (in block mode)',
    example: { before: '|hello]\n|world]', after: '[hello|\n[world|' },
    category: 'movement',
    colorClass: 'emerald',
  },

  // Operations on selection
  {
    key: 'd',
    modes: [VIM_MODES.VISUAL],
    description: 'Delete selection',
    example: { before: 'hello [world] vim', after: 'hello | vim' },
    category: 'delete',
    colorClass: 'red',
  },
  {
    key: 'x',
    modes: [VIM_MODES.VISUAL],
    description: 'Delete selection (same as d)',
    example: { before: 'hello [world] vim', after: 'hello | vim' },
    category: 'delete',
    colorClass: 'red',
  },
  {
    key: 'y',
    modes: [VIM_MODES.VISUAL],
    description: 'Yank (copy) selection',
    example: { before: 'hello [world] vim', after: 'hello |world vim (copied)' },
    category: 'editing',
    colorClass: 'amber',
  },
  {
    key: 'c',
    modes: [VIM_MODES.VISUAL],
    description: 'Change selection (delete and enter insert mode)',
    example: { before: 'hello [world] vim', after: 'hello | vim (INSERT)' },
    category: 'editing',
    colorClass: 'red',
  },
  {
    key: 's',
    modes: [VIM_MODES.VISUAL],
    description: 'Substitute selection (same as c)',
    example: { before: 'hello [world] vim', after: 'hello | vim (INSERT)' },
    category: 'editing',
    colorClass: 'red',
  },
  {
    key: 'r',
    modes: [VIM_MODES.VISUAL],
    description: 'Replace every character in selection with typed character',
    example: { before: 'hello [world]', after: 'hello |xxxxx' },
    category: 'editing',
    colorClass: 'red',
  },

  // Paste in visual mode
  {
    key: 'p',
    modes: [VIM_MODES.VISUAL],
    description: 'Replace selection with paste buffer',
    example: { before: 'hello [world]', after: 'hello |yanked_text' },
    category: 'editing',
    colorClass: 'amber',
  },
  {
    key: 'P',
    modes: [VIM_MODES.VISUAL],
    description: 'Replace selection with paste buffer (same as p)',
    example: { before: 'hello [world]', after: 'hello |yanked_text' },
    category: 'editing',
    colorClass: 'amber',
  },

  // Indent operations
  {
    key: '<',
    modes: [VIM_MODES.VISUAL],
    description: 'Decrease indent of selection',
    example: { before: '    [hello world]', after: '  [hello world]' },
    category: 'editing',
    colorClass: 'amber',
  },
  {
    key: '>',
    modes: [VIM_MODES.VISUAL],
    description: 'Increase indent of selection',
    example: { before: '[hello world]', after: '  [hello world]' },
    category: 'editing',
    colorClass: 'amber',
  },

  // Case changes
  {
    key: 'u',
    modes: [VIM_MODES.VISUAL],
    description: 'Make selection lowercase',
    example: { before: 'hello [WORLD]', after: 'hello [world]' },
    category: 'editing',
    colorClass: 'amber',
  },
  {
    key: 'U',
    modes: [VIM_MODES.VISUAL],
    description: 'Make selection uppercase',
    example: { before: 'hello [world]', after: 'hello [WORLD]' },
    category: 'editing',
    colorClass: 'amber',
  },
  {
    key: '~',
    modes: [VIM_MODES.VISUAL],
    description: 'Toggle case of selection',
    example: { before: 'hello [World]', after: 'hello [wORLD]' },
    category: 'editing',
    colorClass: 'amber',
  },

  // Text objects in visual mode
  {
    key: 'i',
    modes: [VIM_MODES.VISUAL],
    description: 'Inner text object (iw = inner word, i" = inner quotes, etc.)',
    example: { before: 'h[e]llo', after: '[hello]' },
    category: 'movement',
    colorClass: 'emerald',
  },
  {
    key: 'a',
    modes: [VIM_MODES.VISUAL],
    description: 'Around text object (aw = around word, a" = around quotes, etc.)',
    example: { before: 'h[e]llo world', after: '[hello ]world' },
    category: 'movement',
    colorClass: 'emerald',
  },

  // Join lines
  {
    key: 'J',
    modes: [VIM_MODES.VISUAL],
    description: 'Join selected lines',
    example: { before: '[hello\nworld]', after: 'hello world|' },
    category: 'editing',
    colorClass: 'amber',
  },

  // Search commands in visual mode
  {
    key: '/',
    modes: [VIM_MODES.VISUAL],
    description: 'Search forward (extends selection to match)',
    example: { before: 'he[llo] vim world', after: 'he[llo vim] world' },
    category: 'search',
    colorClass: 'purple',
  },
  {
    key: '?',
    modes: [VIM_MODES.VISUAL],
    description: 'Search backward (extends selection to match)',
    example: { before: 'vim hello [world]', after: '[vim hello world]' },
    category: 'search',
    colorClass: 'purple',
  },
  {
    key: 'n',
    modes: [VIM_MODES.VISUAL],
    description: 'Next search match (extends selection)',
    example: { before: 'vim [hello] vim', after: 'vim [hello vim]' },
    category: 'search',
    colorClass: 'purple',
  },
  {
    key: 'N',
    modes: [VIM_MODES.VISUAL],
    description: 'Previous search match (extends selection)',
    example: { before: 'vim hello [vim]', after: '[vim hello vim]' },
    category: 'search',
    colorClass: 'purple',
  },

  // Exit visual mode
  {
    key: 'v',
    modes: [VIM_MODES.VISUAL],
    description: 'Exit visual mode (return to normal)',
    example: { before: 'he[llo] (VISUAL)', after: 'hel|lo (NORMAL)' },
    category: 'mode',
    colorClass: 'purple',
  },
  {
    key: 'Escape',
    modes: [VIM_MODES.VISUAL],
    description: 'Exit visual mode (return to normal)',
    example: { before: 'he[llo] (VISUAL)', after: 'hel|lo (NORMAL)' },
    category: 'mode',
    colorClass: 'blue',
  },
]

export const proficiencyPresets: ProficiencyPreset[] = [
  {
    level: 'beginner',
    title: 'Beginner',
    description: 'Essential movement and basic insert mode',
    highlightedKeys: ['h', 'j', 'k', 'l', 'i', 'Escape'],
  },
  {
    level: 'intermediate',
    title: 'Intermediate',
    description: 'Word navigation, line operations, insert commands, and basic visual mode',
    highlightedKeys: [
      'h',
      'j',
      'k',
      'l',
      'w',
      'b',
      'e',
      '0',
      '$',
      'i',
      'I',
      'a',
      'A',
      'o',
      'O',
      'x',
      'v', // Visual mode entry
      'Escape',
    ],
  },
  {
    level: 'advanced',
    title: 'Advanced',
    description: 'Search, operators, efficient editing, and visual mode operations',
    highlightedKeys: [
      'h',
      'j',
      'k',
      'l',
      'w',
      'W',
      'b',
      'B',
      'e',
      'E',
      '0',
      '$',
      '^',
      'f',
      'F',
      't',
      'T',
      '/',
      '?',
      'n',
      'N',
      'i',
      'I',
      'a',
      'A',
      'o',
      'O',
      'x',
      'X',
      'd',
      'D',
      'c',
      'C',
      'u',
      'v', // Visual mode
      'V', // Visual line mode
      'y', // Yank
      'p', // Paste
      'Escape',
    ],
  },
  {
    level: 'vim-btw',
    title: 'I use Vim btw...',
    description: 'All documented Vim commands - complete power user mode!',
    highlightedKeys: [
      // Movement keys
      'h',
      'j',
      'k',
      'l',
      'w',
      'W',
      'b',
      'B',
      'e',
      'E',
      '0',
      '$', // Shift+4
      '^', // Shift+6
      '_', // Shift+-
      'g',
      'G',
      'H',
      'M',
      'L',
      '%', // Shift+5
      '{', // Shift+[
      '}', // Shift+]
      // Search keys
      'f',
      'F',
      't',
      'T',
      ';',
      ',',
      '*', // Shift+8
      '/',
      '?', // Shift+/
      'n',
      'N',
      // Mode change keys
      'i',
      'I',
      'a',
      'A',
      'o',
      'O',
      'v', // Visual mode
      'V', // Visual line mode
      'Escape',
      // Delete/edit keys
      'x',
      'X',
      's',
      'S',
      'd',
      'D',
      'c',
      'C',
      'J',
      'y',
      'p',
      'P',
      'r',
      // History/misc keys
      'u',
      '.',
      'm',
      "'",
      '@', // Shift+2
      // Visual mode operations
      '<', // Decrease indent (Shift+,)
      '>', // Increase indent (Shift+.)
      '~', // Toggle case (Shift+`)
      // Special keys
      'Backspace',
      'Enter',
      // Base number/symbol keys that have shift variants used in Vim
      '0', // Also used for "move to start of line"
      '4', // Has $ on shift
      '5', // Has % on shift
      '6', // Has ^ on shift
      '8', // Has * on shift
      '-', // Has _ on shift
      '[', // Has { on shift
      ']', // Has } on shift
      '2', // Has @ on shift
      '`', // Has ~ on shift
    ],
  },
]

// Helper to get command for a key in a specific mode (case-sensitive)
export const getCommandForKey = (
  key: string,
  mode: string,
): VimCommand | undefined => {
  return vimCommands.find(
    (cmd) => cmd.key === key && cmd.modes.includes(mode as VimMode),
  )
}
